# Generated by Django 4.0.6 on 2024-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactsinformations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('diseases', models.CharField(max_length=128)),
                ('foodType', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='contactEnquiry',
        ),
    ]
